# Introduction to Julia

Strongly inspired from Juan Pablo Vielma's [JuMPdev 2019 tutorial](https://github.com/JuliaLang/IJulia.jl).

In [1]:
include("setup.jl")

┌ Info: Installing packages. This may take up to a few minutes.
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:1


  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`


┌ Info: Loading packages
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:7
┌ Info: All packages successfully imported.
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:24


* How to use Julia
* Basic syntax and types
* Control flow
* Functions
* More on types
* Linear algebra
* Package management
* Advanced features

## How to use Julia

### REPL

The Read-Eval-Print-Loop (REPL) is the julia interactive shell

```bash
julia
```

<img src="img/REPL.png">

### Command line

You can execute a julia script from the command line
```bash
julia script.jl
```

To pass command line arguments
```bash
julia script.jl arg1 arg2 arg3
```
Command-line arguments are accessed within julia via the variable `ARGS`.

### Jupyter

Julia is the "Ju" in "Jupyter"!

To run Julia in a notebook:

* Install Jupyter (e.g. via Anaconda)
* Install the `IJulia` package
* Launch Jupyter

(if you skip the Jupyter installation, Julia will install a julia-only `conda` distribution)

For running Jupyter notebooks on GERAD machines: https://www.gerad.ca/aide/doku.php?id=en:programmation-python

## Basic syntax and types

### Basic types

Booleans

In [2]:
true

true

In [3]:
typeof(true)

Bool

Integers

In [4]:
1 + 1

2

In [5]:
typeof(1)

Int64

Floating point

In [6]:
1.0 + 2.0

3.0

In [7]:
typeof(1.0)

Float64

Floating-point arithmetic has limited precision!

In [8]:
(1.0 + 1e-16) == 1.0

true

In [9]:
(1.0 + 1e-16) - 1e-16 == 1.0 + (1e-16 - 1e-16)

false

Type correspondence:

| Julia   | C       |
|:-------:|:-------:|
| Int32   | int     |
| Int64   | long    | 
| Float32 | float   |
| Float64 | double  |

Strings are defined with double quotes

In [10]:
"Hello world!"

"Hello world!"

Concatenate strings with `*`

In [11]:
"Hello" * " " * "world!"

"Hello world!"

String interpolation eases the need for concatenation

In [12]:
x, y, z = "Alice", "Bob", "Charles"
"Hello $(x), $y and $(z)!"

"Hello Alice, Bob and Charles!"

Symbols are human-readable unique identifiers

In [13]:
:symbol
typeof(:symbol)

Symbol

### Elementary data structures

Tuples are immutable collections of values

In [14]:
t1 = (1, 2, 3)
t2 = ("hello", 1, :x)

("hello", 1, :x)

In [15]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [16]:
typeof(t2)

Tuple{String,Int64,Symbol}

Arrays are collections of values **of the same type** that are stored contiguously in memory.

In [17]:
u = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [18]:
typeof(u)

Array{Int64,1}

**/!\ Array indexing starts at 1 /!\**

In [19]:
u[1]

1

Elements automatically get promoted to the same type if necessary

In [20]:
v = [1.0, 2, 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [21]:
typeof(v)

Array{Float64,1}

If no common type can be inferred, the element type is `Any`

In [22]:
w = ["hello", 1, :x]

3-element Array{Any,1}:
  "hello"
 1       
  :x     

In [23]:
typeof(w)

Array{Any,1}

Dictionnaries

In [24]:
d = Dict("a" => 1, "b" => 2, "c" => 3)

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [25]:
d["a"]

1

In [26]:
d["a"] = 2
d

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 2

In [27]:
d["d"] = 4

4

## Control flow

### If-then-else

In [28]:
if x == 0
    println("Hello 0!")
elseif x == 1
    println("Hello 1!")
elseif x == -1
    println("Hello -1!")
else
    println("Hello x")
end 

Hello x


### For loops

In [29]:
for i in 1:5
    println("Hello $(i)!")
end

Hello 1!
Hello 2!
Hello 3!
Hello 4!
Hello 5!


Iterate over arrays

In [30]:
u = [1, 4, 9, 16]
for x in u
    println(x)
end

1
4
9
16


Iterate over dictionnaries

In [31]:
d = Dict("a" => 1, "b" => 2, "c" => 3)
for (key, val) in d
    println("Key: $key, val: $val")
end

Key: c, val: 3
Key: b, val: 2
Key: a, val: 1


More generally: **iterate over any collection**

### Comprehensions

Build a list of increasing integers

In [32]:
u = [i for i in 1:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [33]:
v = [1 for _ in 1:4]

4-element Array{Int64,1}:
 1
 1
 1
 1

Build a matrix

In [34]:
A = [i*j for i in 1:4, j in 1:4]

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

Filter out some values

In [35]:
v = [i for i in 1:10 if i % 2 == 1]  # odd integers between 1 and 10

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

Dictionnaries

In [36]:
d = Dict("$i" => i^2 for i in 1:5)

Dict{String,Int64} with 5 entries:
  "4" => 16
  "1" => 1
  "5" => 25
  "2" => 4
  "3" => 9

## Functions

To define a function:

In [37]:
function print_hello()
    println("Hello world!")
end
print_hello()

Hello world!


Functions can have arguments

In [38]:
function print_it(x, y)
    println(x)
    println(y)
end
print_it("Hello", 1)
print_it([1, 2], 47.0)

Hello
1
[1, 2]
47.0


Optional arguments are possible

In [39]:
function print_info(x; prefix="Value : ")
    println("$(prefix)$x")
end
print_info(3.1415)
print_info(3.1415, prefix="π = ")

Value : 3.1415
π = 3.1415


The return value of a function is specified with the keyword `return`

In [40]:
function my_mul(x, y)
    return x * y
end
my_mul(1, 2)

2

Otherwise, the function returns the result of the last expression

Docstrings are written before the body of the function, and start/end with `"""`.
You can use Markdown syntax within docstrings.

In [41]:
"""
    my_mul(x, y, z)

Compute the product `x*y*z`
"""
function my_mul(x, y, z)
    return x * y * z
end

my_mul

Always write docstrings!

### Getting help

You can display a function's docstring by pre-prending `?` to its name

In [42]:
?my_mul

search: my_mul



```
my_mul(x, y, z)
```

Compute the product `x*y*z`


## More on types

Everything in Julia has a type.

You don't **need** to specify types when declaring variables or function arguments... but sometimes it helps.

To avoid errors

In [43]:
"""
    my_fact(n)

Compute the factorial of `n`, i.e., `1*2*...*(n-1)*n`.
"""
function my_fact(n)
    if n == 1
        return 1
    else
        return n * my_fact(n - 1)
    end
end
my_fact(10)

3628800

In [44]:
my_fact(1.5)

StackOverflowError: StackOverflowError:

## Declaring your own types

### Abstract types

In [45]:
abstract type AbstractFoo end

Abstract types
* cannot have attributes
* cannot be instantiated

In [46]:
AbstractFoo()

MethodError: MethodError: no constructors have been defined for AbstractFoo

### Immutable types

are called `struct` in Julia (like C)

In [47]:
struct Foo
    x
end

In [48]:
foo = Foo(1.0)

Foo(1.0)

You cannot modify the attributes of an `immutable` type

In [49]:
foo.x = 2

ErrorException: type Foo is immutable

### Mutable types

are `struct`s whose attributes can be modified.

In [50]:
mutable struct FooBar
    x
end

In [51]:
foo = FooBar(1.0)
typeof(foo)

FooBar

In [52]:
foo.x = 2

2

### Parametrized types

Types can be parametrized by other types

In [53]:
Vector

Array{T,1} where T

You can parametrize by multiple types

In [54]:
struct MyFoo{Ti<:Integer, Tv<:AbstractFloat}
    i::Ti
    v::Tv
end
typeof(MyFoo(1, 1.0))

MyFoo{Int64,Float64}

In [55]:
typeof(MyFoo(0x01, 1.0f0))

MyFoo{UInt8,Float32}

### What about functions?

Functions are not "attached" to classes like in object-oriented languages.

Functions have _methods_ that are dispatched based on the types of **all** arguments: it's called **multiple dispatch**

In [56]:
@which +(1.0, 1.0)

+(x::Float64, y::Float64) in Base at float.jl:395

In [57]:
@which +(1.0, 1)

+(x::Number, y::Number) in Base at promotion.jl:313

In [58]:
+

+ (generic function with 217 methods)

In [59]:
methods(+)

# 217 methods for generic function "+":
[1] +(x::Bool, z::Complex{Bool}) in Base at complex.jl:277
[2] +(x::Bool, y::Bool) in Base at bool.jl:104
[3] +(x::Bool) in Base at bool.jl:101
[4] +(x::Bool, y::T) where T<:AbstractFloat in Base at bool.jl:112
[5] +(x::Bool, z::Complex) in Base at complex.jl:284
[6] +(a::Float16, b::Float16) in Base at float.jl:392
[7] +(x::Float32, y::Float32) in Base at float.jl:394
[8] +(x::Float64, y::Float64) in Base at float.jl:395
[9] +(z::Complex{Bool}, x::Bool) in Base at complex.jl:278
[10] +(z::Complex{Bool}, x::Real) in Base at complex.jl:292
[11] +(::Missing, ::Missing) in Base at missing.jl:92
[12] +(::Missing) in Base at missing.jl:79
[13] +(::Missing, ::Number) in Base at missing.jl:93
[14] +(level::Base.CoreLogging.LogLevel, inc::Integer) in Base.CoreLogging at logging.jl:106
[15] +(c::BigInt, x::BigFloat) in Base.MPFR at mpfr.jl:353
[16] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) in Base.GMP at gmp.jl:443
[17] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt) in Base.GMP at gmp.jl:442
[18] +(a::BigInt, b::BigInt, c::BigInt) in Base.GMP at gmp.jl:441
[19] +(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:412
[20] +(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.GMP at gmp.jl:449
[21] +(x::BigInt, c::Union{Int16, Int32, Int64, Int8}) in Base.GMP at gmp.jl:455
[22] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) in Base.MPFR at mpfr.jl:503
[23] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) in Base.MPFR at mpfr.jl:496
[24] +(a::BigFloat, b::BigFloat, c::BigFloat) in Base.MPFR at mpfr.jl:490
[25] +(x::BigFloat, c::BigInt) in Base.MPFR at mpfr.jl:349
[26] +(x::BigFloat, y::BigFloat) in Base.MPFR at mpfr.jl:318
[27] +(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.MPFR at mpfr.jl:325
[28] +(x::BigFloat, c::Union{Int16, Int32, Int64, Int8}) in Base.MPFR at mpfr.jl:333
[29] +(x::BigFloat, c::Union{Float16, Float32, Float64}) in Base.MPFR at mpfr.jl:341
[30] +(x::Dates.CompoundPeriod, y::Dates.CompoundPeriod) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/periods.jl:355
[31] +(x::Dates.CompoundPeriod, y::Dates.Period) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/periods.jl:353
[32] +(x::Dates.CompoundPeriod, y::Dates.TimeType) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/periods.jl:391
[33] +(x::Dates.Date, y::Dates.Day) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:78
[34] +(x::Dates.Date, y::Dates.Week) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:76
[35] +(dt::Dates.Date, z::Dates.Month) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:59
[36] +(dt::Dates.Date, y::Dates.Year) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:32
[37] +(dt::Dates.Date, t::Dates.Time) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:20
[38] +(t::Dates.Time, dt::Dates.Date) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:24
[39] +(x::Dates.Time, y::Dates.TimePeriod) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:82
[40] +(dt::Dates.DateTime, z::Dates.Month) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:52
[41] +(dt::Dates.DateTime, y::Dates.Year) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:28
[42] +(x::Dates.DateTime, y::Dates.Period) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Dates/src/arithmetic.jl:80
[43] +(B::BitArray{2}, J::UniformScaling) in LinearAlgeb

## Linear algebra

To use linear algebra functions, use the `LinearAlgebra` package (part of the standard library)

In [60]:
using LinearAlgebra

### Vectors and Matrices

A vector is a uni-dimensional array

In [61]:
Vector{Float32}

Array{Float32,1}

In [62]:
x = [1.0, 2.0]

2-element Array{Float64,1}:
 1.0
 2.0

A matrix is a two-dimensional array

In [63]:
Matrix{Float64}

Array{Float64,2}

In [64]:
A = [
    1.0 2.0;
    3.0 4.0
]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

### Linear algebra operations

Matrix-vector products work out of the box

In [65]:
A * x

2-element Array{Float64,1}:
  5.0
 11.0

Solve linear systems

In [66]:
b = A * x
y = A \ b

2-element Array{Float64,1}:
 1.0
 2.0

You can't multiply two vectors

In [67]:
x * x

MethodError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Adjoint{#s546,#s545} where #s545<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s546, ::Union{DenseArray{S,1}, ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:99
  *(!Matched::Adjoint{#s546,#s545} where #s545<:LinearAlgebra.AbstractTriangular where #s546, ::AbstractArray{T,1} where T) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/triangular.jl:1805
  ...

But inner and outer product is OK

In [68]:
x' * x  # inner product

5.0

In [69]:
x * x'  # outer product

2×2 Array{Float64,2}:
 1.0  2.0
 2.0  4.0

### BLAS / LAPACK

For real/complex numbers in `Float32`, `Float64` precision:
* dense vector-vector, matrix-vector, matrix-matrix operations call BLAS
* dense matrix factorizations call LAPACK

You can also call BLAS/LAPACK functions directly

In [70]:
C = zeros(2, 2);
A = ones(2, 4);
BLAS.syrk!('U', 'N', 1.0, A, 0.0, C)  # computes C = α A*A' + β C

2×2 Array{Float64,2}:
 4.0  4.0
 0.0  4.0

### Sparse linear algebra

In [71]:
using SparseArrays

In [72]:
A = sparse([1, 2, 3], [1, 2, 3], [1.0, 1.0, 1.0])

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  1.0
  [3, 3]  =  1.0

In [73]:
Matrix(A)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

Sparse factorization call the `CHOLMOD` module from `SuiteSparse`.

Community wrappers to MUMPS, Pardiso, HSL linear solvers.

## Package management

Julia's package manager is `Pkg` (https://julialang.github.io/Pkg.jl/v1/).

In [74]:
using Pkg

Packages are organized into **environments**.

An **environment** is a set of packages.

### Install / remove packages

Install a package with `Pkg.add`

In [75]:
Pkg.add("Tulip")

 Resolving package versions...
  Updating `~/GitHub/tipsntricks/julia/Project.toml`
  [6dd1b50a] + Tulip v0.1.0
  Updating `~/GitHub/tipsntricks/julia/Manifest.toml`
  [739be429] ↓ MbedTLS v0.7.0 ⇒ v0.6.8
  [6dd1b50a] + Tulip v0.1.0


Update a package

In [76]:
Pkg.update("Tulip")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/GitHub/tipsntricks/julia/Project.toml`
 [no changes]
  Updating `~/GitHub/tipsntricks/julia/Manifest.toml`
 [no changes]


Remove a package

In [77]:
Pkg.rm("Tulip")

  Updating `~/GitHub/tipsntricks/julia/Project.toml`
  [6dd1b50a] - Tulip v0.1.0
  Updating `~/GitHub/tipsntricks/julia/Manifest.toml`
  [6dd1b50a] - Tulip v0.1.0


### Projects and `Project.toml`

> The project file describes the project on a high level, for example the package/project dependencies and compatibility constraints are listed in the project file.

The `Project.toml` file contains the list of all packages in that environment and compatibility requirements (if any).

In [78]:
; cat Project.toml

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


### Package versions and `Manifest.toml`

> The **exact set of packages and versions** in an environment is captured in a **manifest file** which can be checked into a project repository and tracked in version control

The `Manifest.toml` file contains the **exact version** of every installed package, including all hidden dependencies.

If your `Manifest.toml` file is the same, your package version are the same.

### Working with environments

From Julia: use `Pkg.activate`

In [79]:
# activate environment located in current folder
Pkg.activate(".")

"/home/mathieu/GitHub/tipsntricks/julia/Project.toml"

When using Julia from the command line
```bash
julia --project=. script.jl
```

### Re-using someone else's environment

First download and install all packages

In [80]:
Pkg.activate(".")  # activate environment
Pkg.instantiate()  # download and install packages

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`


Good to go!

## Code structure

### When starting a new project

* Create a new environment at the root of the repository
* Use version control on `Project.toml` and `Manifest.toml`

```
--docs/
--src/
--test/
Project.toml
Manifest.toml
README.md
```

## Code loading

https://docs.julialang.org/en/v1/manual/code-loading/

### Code inclusion

Code from a different file can be loaded

In [81]:
include("hello.jl")

Hello world! Current time is 1.571416208883725e9s


In [82]:
include("hello.jl")

Hello world! Current time is 1.571416210906346e9s


This causes the contents of the file to be evaluated in the global scope.

Your code gets executed every time you call `include`.

### Package loading

You can load packages with `import / using`

In [83]:
import GLPK
Prob

Prob

In [84]:
GLPK.Prob

Prob

`using` allows you to use exported names in the current namespace

In [85]:
using GLPK
Prob

Prob

## Compilation and timing

In Julia code is compiled **just-in-time** => some compilation happens while you execute your code.

Be careful when timing code execution!

In [86]:
"""Compute the sum of the elements in a vector."""
function my_sum(u::Vector{T}) where{T}
    s = zero(T)
    for x in u
        s += x
    end
    return s
end

u = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
v = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0];

The first time a function is called, it is compiled.
Subsequent calls are fast.

In [87]:
@time my_sum(u)  # First time: compilation happens
@time my_sum(u)  # Second time: no compilation

  0.008771 seconds (5.87 k allocations: 281.956 KiB)
  0.000002 seconds (4 allocations: 160 bytes)


55

In [88]:
@time my_sum(v)  # First time (with Float64): compilation happens
@time my_sum(v)  # Second time: no compilation

  0.006903 seconds (5.86 k allocations: 281.679 KiB)
  0.000002 seconds (5 allocations: 176 bytes)


55.0

### Timing code properly

If you only care about the result => compilation doesn't impact you.

If you care about execution time => compilation does impact you.

Possible fix:
* Run your function twice, time only the second execution
* Run your function on a small example, then on your real problem

### Command line execution

Everytime you run
```bash
julia --project=. hello.jl
```
Julia has to re-compile your code from scratch.

Make sure what you're timing does not include compilation times!