# Introduction to Julia

Strongly inspired from Juan Pablo Vielma's [JuMPdev 2019 tutorial](https://github.com/JuliaLang/IJulia.jl).

In [1]:
include("setup.jl")

┌ Info: Installing packages. This may take up to a few minutes.
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:1


  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`


┌ Info: Loading packages
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:7
┌ Info: All packages successfully imported.
└ @ Main /home/mathieu/GitHub/tipsntricks/julia/setup.jl:24


* How to use Julia
* Basic syntax and types
* Control flow
* Functions
* More on types
* Linear algebra
* Package management
* Advanced features

## How to use Julia

### REPL

The Read-Eval-Print-Loop (REPL) is the julia interactive shell

```bash
julia
```

<img src="img/REPL.png">

### Command line

You can execute a julia script from the command line
```bash
julia script.jl
```

To pass command line arguments
```bash
julia script.jl arg1 arg2 arg3
```
Command-line arguments are accessed within julia via the variable `ARGS`.

### Jupyter

Julia is the "Ju" in "Jupyter"!

To run Julia in a notebook:

* Install Jupyter (e.g. via Anaconda)
* Install the `IJulia` package
* Launch Jupyter

(if you skip the Jupyter installation, Julia will install a julia-only `conda` distribution)

For running Jupyter notebooks on GERAD machines: https://www.gerad.ca/aide/doku.php?id=en:programmation-python

## Basic syntax and types

### Basic types

Booleans

In [2]:
true

true

In [3]:
typeof(true)

Bool

Integers

In [4]:
1 + 1

2

In [5]:
typeof(1)

Int64

Floating point

In [6]:
1.0 + 2.0

3.0

In [7]:
typeof(1.0)

Float64

Floating-point arithmetic has limited precision!

In [8]:
(1.0 + 1e-16) == 1.0

true

In [9]:
(1.0 + 1e-16) - 1e-16 == 1.0 + (1e-16 - 1e-16)

false

Type correspondence:

| Julia   | C       |
|:-------:|:-------:|
| Int32   | int     |
| Int64   | long    | 
| Float32 | float   |
| Float64 | double  |

Strings are defined with double quotes

In [10]:
"Hello world!"

"Hello world!"

Concatenate strings with `*`

In [11]:
"Hello" * " " * "world!"

"Hello world!"

String interpolation eases the need for concatenation

In [12]:
x, y, z = "Alice", "Bob", "Charles"
"Hello $(x), $y and $(z)!"

"Hello Alice, Bob and Charles!"

Symbols are human-readable unique identifiers

In [13]:
:symbol
typeof(:symbol)

Symbol

### Elementary data structures

Tuples are immutable collections of values

In [14]:
t1 = (1, 2, 3)
t2 = ("hello", 1, :x)

("hello", 1, :x)

In [15]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [16]:
typeof(t2)

Tuple{String,Int64,Symbol}

Arrays are collections of values **of the same type** that are stored contiguously in memory.

In [17]:
u = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [18]:
typeof(u)

Array{Int64,1}

**/!\ Array indexing starts at 1 /!\**

In [19]:
u[1]

1

Elements automatically get promoted to the same type if necessary

In [20]:
v = [1.0, 2, 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [21]:
typeof(v)

Array{Float64,1}

If no common type can be inferred, the element type is `Any`

In [22]:
w = ["hello", 1, :x]

3-element Array{Any,1}:
  "hello"
 1       
  :x     

In [23]:
typeof(w)

Array{Any,1}

Dictionnaries

In [24]:
d = Dict("a" => 1, "b" => 2, "c" => 3)

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [25]:
d["a"]

1

In [26]:
d["a"] = 2
d

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 2

In [27]:
d["d"] = 4

4

## Control flow

### If-then-else

In [28]:
if x == 0
    println("Hello 0!")
elseif x == 1
    println("Hello 1!")
elseif x == -1
    println("Hello -1!")
else
    println("Hello x")
end 

Hello x


### For loops

In [29]:
for i in 1:5
    println("Hello $(i)!")
end

Hello 1!
Hello 2!
Hello 3!
Hello 4!
Hello 5!


Iterate over arrays

In [30]:
u = [1, 4, 9, 16]
for x in u
    println(x)
end

1
4
9
16


Iterate over dictionnaries

In [31]:
d = Dict("a" => 1, "b" => 2, "c" => 3)
for (key, val) in d
    println("Key: $key, val: $val")
end

Key: c, val: 3
Key: b, val: 2
Key: a, val: 1


More generally: **iterate over any collection**

### Comprehensions

Build a list of increasing integers

In [32]:
u = [i for i in 1:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [33]:
v = [1 for _ in 1:4]

4-element Array{Int64,1}:
 1
 1
 1
 1

Build a matrix

In [34]:
A = [i*j for i in 1:4, j in 1:4]

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

Filter out some values

In [35]:
v = [i for i in 1:10 if i % 2 == 1]  # odd integers between 1 and 10

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

Dictionnaries

In [36]:
d = Dict("$i" => i^2 for i in 1:5)

Dict{String,Int64} with 5 entries:
  "4" => 16
  "1" => 1
  "5" => 25
  "2" => 4
  "3" => 9

## Functions

To define a function:

In [37]:
function print_hello()
    println("Hello world!")
end
print_hello()

Hello world!


Functions can have arguments

In [38]:
function print_it(x, y)
    println(x)
    println(y)
end
print_it("Hello", 1)
print_it([1, 2], 47.0)

Hello
1
[1, 2]
47.0


Optional arguments are possible

In [39]:
function print_info(x; prefix="Value : ")
    println("$(prefix)$x")
end
print_info(3.1415)
print_info(3.1415, prefix="π = ")

Value : 3.1415
π = 3.1415


The return value of a function is specified with the keyword `return`

In [40]:
function my_mul(x, y)
    return x * y
end
my_mul(1, 2)

2

Otherwise, the function returns the result of the last expression

Docstrings are written before the body of the function, and start/end with `"""`.
You can use Markdown syntax within docstrings.

In [41]:
"""
    my_mul(x, y, z)

Compute the product `x*y*z`
"""
function my_mul(x, y, z)
    return x * y * z
end

my_mul

Always write docstrings!

### Getting help

You can display a function's docstring by pre-prending `?` to its name

In [42]:
?my_mul

search: my_mul



```
my_mul(x, y, z)
```

Compute the product `x*y*z`


## More on types

Everything in Julia has a type.

You don't **need** to specify types when declaring variables or function arguments... but sometimes it helps.

To avoid errors

In [43]:
"""
    my_fact(n)

Compute the factorial of `n`, i.e., `1*2*...*(n-1)*n`.
"""
function my_fact(n)
    if n == 1
        return 1
    else
        return n * my_fact(n - 1)
    end
end
my_fact(10)

3628800

In [ ]:
my_fact(1.5)

## Declaring your own types

### Abstract types

In [ ]:
abstract type AbstractFoo end

Abstract types
* cannot have attributes
* cannot be instantiated

In [ ]:
AbstractFoo()

### Immutable types

are called `struct` in Julia (like C)

In [ ]:
struct Foo
    x
end

In [ ]:
foo = Foo(1.0)

You cannot modify the attributes of an `immutable` type

In [ ]:
foo.x = 2

### Mutable types

are `struct`s whose attributes can be modified.

In [ ]:
mutable struct FooBar
    x
end

In [ ]:
foo = FooBar(1.0)
typeof(foo)

In [ ]:
foo.x = 2

### Parametrized types

Types can be parametrized by other types

In [ ]:
Vector

You can parametrize by multiple types

In [ ]:
struct MyFoo{Ti<:Integer, Tv<:AbstractFloat}
    i::Ti
    v::Tv
end
typeof(MyFoo(1, 1.0))

In [ ]:
typeof(MyFoo(0x01, 1.0f0))

### What about functions?

Functions are not "attached" to classes like in object-oriented languages.

Functions have _methods_ that are dispatched based on the types of **all** arguments: it's called **multiple dispatch**

In [ ]:
@which +(1.0, 1.0)

In [ ]:
@which +(1.0, 1)

In [ ]:
+

In [ ]:
methods(+)

## Linear algebra

To use linear algebra functions, use the `LinearAlgebra` package (part of the standard library)

In [ ]:
using LinearAlgebra

### Vectors and Matrices

A vector is a uni-dimensional array

In [ ]:
Vector{Float32}

In [ ]:
x = [1.0, 2.0]

A matrix is a two-dimensional array

In [ ]:
Matrix{Float64}

In [ ]:
A = [
    1.0 2.0;
    3.0 4.0
]

### Linear algebra operations

Matrix-vector products work out of the box

In [ ]:
A * x

Solve linear systems

In [ ]:
b = A * x
y = A \ b

You can't multiply two vectors

In [ ]:
x * x

But inner and outer product is OK

In [ ]:
x' * x  # inner product

In [ ]:
x * x'  # outer product

### BLAS / LAPACK

For real/complex numbers in `Float32`, `Float64` precision:
* dense vector-vector, matrix-vector, matrix-matrix operations call BLAS
* dense matrix factorizations call LAPACK

You can also call BLAS/LAPACK functions directly

In [ ]:
C = zeros(2, 2);
A = ones(2, 4);
BLAS.syrk!('U', 'N', 1.0, A, 0.0, C)  # computes C = α A*A' + β C

### Sparse linear algebra

In [ ]:
using SparseArrays

In [ ]:
A = sparse([1, 2, 3], [1, 2, 3], [1.0, 1.0, 1.0])

In [ ]:
Matrix(A)

Sparse factorization call the `CHOLMOD` module from `SuiteSparse`.

Community wrappers to MUMPS, Pardiso, HSL linear solvers.

## Package management

Julia's package manager is `Pkg` (https://julialang.github.io/Pkg.jl/v1/).

In [ ]:
using Pkg

Packages are organized into **environments**.

An **environment** is a set of packages.

### Install / remove packages

Install a package with `Pkg.add`

In [ ]:
Pkg.add("Tulip")

Update a package

In [ ]:
Pkg.update("Tulip")

Remove a package

In [ ]:
Pkg.rm("Tulip")

### Projects and `Project.toml`

> The project file describes the project on a high level, for example the package/project dependencies and compatibility constraints are listed in the project file.

The `Project.toml` file contains the list of all packages in that environment and compatibility requirements (if any).

In [ ]:
; cat Project.toml

### Package versions and `Manifest.toml`

> The **exact set of packages and versions** in an environment is captured in a **manifest file** which can be checked into a project repository and tracked in version control

The `Manifest.toml` file contains the **exact version** of every installed package, including all hidden dependencies.

If your `Manifest.toml` file is the same, your package version are the same.

### Working with environments

From Julia: use `Pkg.activate`

In [ ]:
# activate environment located in current folder
Pkg.activate(".")

When using Julia from the command line
```bash
julia --project=. script.jl
```

### Re-using someone else's environment

First download and install all packages

In [ ]:
Pkg.activate(".")  # activate environment
Pkg.instantiate()  # download and install packages

Good to go!

## Code structure

### When starting a new project

* Create a new environment at the root of the repository
* Use version control on `Project.toml` and `Manifest.toml`

```
--docs/
--src/
--test/
Project.toml
Manifest.toml
README.md
```

## Code loading

https://docs.julialang.org/en/v1/manual/code-loading/

### Code inclusion

Code from a different file can be loaded

In [ ]:
include("hello.jl")

In [ ]:
include("hello.jl")

This causes the contents of the file to be evaluated in the global scope.

Your code gets executed every time you call `include`.

### Package loading

You can load packages with `import / using`

In [ ]:
import GLPK
Prob

In [ ]:
GLPK.Prob

`using` allows you to use exported names in the current namespace

In [ ]:
using GLPK
Prob

## Compilation and timing

In Julia code is compiled **just-in-time** => some compilation happens while you execute your code.

Be careful when timing code execution!

In [ ]:
"""Compute the sum of the elements in a vector."""
function my_sum(u::Vector{T}) where{T}
    s = zero(T)
    for x in u
        s += x
    end
    return s
end

u = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
v = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0];

The first time a function is called, it is compiled.
Subsequent calls are fast.

In [ ]:
@time my_sum(u)  # First time: compilation happens
@time my_sum(u)  # Second time: no compilation

In [ ]:
@time my_sum(v)  # First time (with Float64): compilation happens
@time my_sum(v)  # Second time: no compilation

### Timing code properly

If you only care about the result => compilation doesn't impact you.

If you care about execution time => compilation does impact you.

Possible fix:
* Run your function twice, time only the second execution
* Run your function on a small example, then on your real problem

### Command line execution

Everytime you run
```bash
julia --project=. hello.jl
```
Julia has to re-compile your code from scratch.

Make sure what you're timing does not include compilation times!