# Introduction to Julia

Strongly inspired from Juan Pablo Vielma's [JuMPdev 2019 tutorial](https://github.com/JuliaLang/IJulia.jl).

* How to use Julia
* Basic syntax and types
* Control flow
* Functions
* More on types
* Linear algebra
* Package management
* Advanced features

## How to use Julia

### REPL

The Read-Eval-Print-Loop (REPL) is the julia interactive shell

```bash
julia
```

<img src="img/REPL.png">

### Command line

You can execute a julia script from the command line
```bash
julia script.jl
```

To pass command line arguments
```bash
julia script.jl arg1 arg2 arg3
```
Command-line arguments are accessed within julia via the variable `ARGS`.

### Jupyter

Julia is the "Ju" in "Jupyter"!

To run Julia in a notebook:

* Install Jupyter (e.g. via Anaconda)
* Install the `IJulia` package
* Launch Jupyter

(if you skip the Jupyter installation, Julia will install a julia-only `conda` distribution)

For running Jupyter notebooks on GERAD machines: https://www.gerad.ca/aide/doku.php?id=en:programmation-python

## Basic syntax and types

### Basic types

Booleans

In [1]:
true

true

In [2]:
typeof(true)

Bool

Integers

In [3]:
1 + 1

2

In [4]:
typeof(1)

Int64

Floating point

In [5]:
1.0 + 2.0

3.0

In [6]:
typeof(1.0)

Float64

Floating-point arithmetic has limited precision!

In [7]:
(1.0 + 1e-16) == 1.0

true

In [8]:
(1.0 + 1e-16) - 1e-16 == 1.0 + (1e-16 - 1e-16)

false

Type correspondence:

| Julia   | C       |
|:-------:|:-------:|
| Int32   | int     |
| Int64   | long    | 
| Float32 | float   |
| Float64 | double  |

Strings are defined with double quotes

In [9]:
"Hello world!"

"Hello world!"

Concatenate strings with `*`

In [10]:
"Hello" * " " * "world!"

"Hello world!"

String interpolation eases the need for concatenation

In [11]:
x, y, z = "Alice", "Bob", "Charles"
"Hello $(x), $y and $(z)!"

"Hello Alice, Bob and Charles!"

Symbols are human-readable unique identifiers

In [12]:
:symbol
typeof(:symbol)

Symbol

### Elementary data structures

Tuples are immutable collections of values

In [13]:
t1 = (1, 2, 3)
t2 = ("hello", 1, :x)

("hello", 1, :x)

In [14]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [15]:
typeof(t2)

Tuple{String,Int64,Symbol}

Arrays are collections of values **of the same type** that are stored contiguously in memory

In [16]:
u = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [17]:
typeof(u)

Array{Int64,1}

Elements automatically get promoted to the same type if necessary

In [18]:
v = [1.0, 2, 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [19]:
typeof(v)

Array{Float64,1}

If no common type can be inferred, the element type is `Any`

In [20]:
w = ["hello", 1, :x]

3-element Array{Any,1}:
  "hello"
 1       
  :x     

In [21]:
typeof(w)

Array{Any,1}

Dictionnaries

In [22]:
d = Dict("a" => 1, "b" => 2, "c" => 3)

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [23]:
d["a"]

1

In [24]:
d["a"] = 2
d

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 2

In [25]:
d["d"] = 4

4

## Control flow

### If-then-else

In [26]:
if x == 0
    println("Hello 0!")
elseif x == 1
    println("Hello 1!")
elseif x == -1
    println("Hello -1!")
else
    println("Hello x")
end 

Hello x


### For loops

In [27]:
for i in 1:5
    println("Hello $(i)!")
end

Hello 1!
Hello 2!
Hello 3!
Hello 4!
Hello 5!


Iterate over arrays

In [28]:
u = [1, 4, 9, 16]
for x in u
    println(x)
end

1
4
9
16


Iterate over dictionnaries

In [29]:
d = Dict("a" => 1, "b" => 2, "c" => 3)
for (key, val) in d
    println("Key: $key, val: $val")
end

Key: c, val: 3
Key: b, val: 2
Key: a, val: 1


More generally: **iterate over any collection**

### Comprehensions

Build a list of increasing integers

In [30]:
u = [i for i in 1:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [31]:
v = [1 for _ in 1:4]

4-element Array{Int64,1}:
 1
 1
 1
 1

Build a matrix

In [32]:
A = [i*j for i in 1:4, j in 1:4]

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

Filter out some values

In [33]:
v = [i for i in 1:10 if i % 2 == 1]  # odd integers between 1 and 10

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

Dictionnaries

In [34]:
d = Dict("$i" => i^2 for i in 1:5)

Dict{String,Int64} with 5 entries:
  "4" => 16
  "1" => 1
  "5" => 25
  "2" => 4
  "3" => 9

## Functions

To define a function:

In [35]:
function print_hello()
    println("Hello world!")
end
print_hello()

Hello world!


Functions can have arguments

In [36]:
function print_it(x, y)
    println(x)
    println(y)
end
print_it("Hello", 1)
print_it([1, 2], 47.0)

Hello
1
[1, 2]
47.0


Optional arguments are possible

In [37]:
function print_info(x; prefix="Value : ")
    println("$(prefix)$x")
end
print_info(3.1415)
print_info(3.1415, prefix="π = ")

Value : 3.1415
π = 3.1415


The return value of a function is specified with the keyword `return`

In [38]:
function my_mul(x, y)
    return x * y
end
my_mul(1, 2)

2

Otherwise, the function returns the result of the last expression

Docstrings are written before the body of the function, and start/end with `"""`.
You can use Markdown syntax within docstrings.

In [39]:
"""
    my_mul(x, y, z)

Compute the product `x*y*z`
"""
function my_mul(x, y, z)
    return x * y * z
end

my_mul

Always write docstrings!

## More on types

Everything in Julia has a type.

You don't **need** to specify types when declaring variables or function arguments... but sometimes it helps.

To avoid errors

In [40]:
"""
    my_fact(n)

Compute the factorial of `n`, i.e., `1*2*...*(n-1)*n`.
"""
function my_fact(n)
    if n == 1
        return 1
    else
        return n * my_fact(n - 1)
    end
end
my_fact(10)

3628800

In [41]:
my_fact(1.5)

StackOverflowError: StackOverflowError:

## Declaring your own types

### Abstract types

In [42]:
abstract type AbstractFoo end

Abstract types
* cannot have attributes
* cannot be instantiated

In [43]:
AbstractFoo()

MethodError: MethodError: no constructors have been defined for AbstractFoo

### Immutable types

are called `struct` in Julia (like C)

In [44]:
struct Foo
    x
end

In [45]:
foo = Foo(1.0)

Foo(1.0)

You cannot modify the attributes of an `immutable` type

In [46]:
foo.x = 2

ErrorException: setfield! immutable struct of type Foo cannot be changed

### Mutable types

are `struct`s whose attributes can be modified.

In [47]:
mutable struct FooBar
    x
end

In [48]:
foo = FooBar(1.0)
typeof(foo)

FooBar

In [49]:
foo.x = 2

2

### Parametrized types

Types can be parametrized by other types

In [50]:
Vector

Array{T,1} where T

You can parametrize by multiple types

In [51]:
struct MyFoo{Ti<:Integer, Tv<:AbstractFloat}
    i::Ti
    v::Tv
end
typeof(MyFoo(1, 1.0))

MyFoo{Int64,Float64}

In [52]:
typeof(MyFoo(0x01, 1.0f0))

MyFoo{UInt8,Float32}

### What about functions?

Functions are not "attached" to classes like in object-oriented languages.

Functions have _methods_ that are dispatched based on the types of **all** arguments: it's called **multiple dispatch**

In [53]:
@which +(1.0, 1.0)

+(x::Float64, y::Float64) in Base at float.jl:395

In [54]:
@which +(1.0, 1)

+(x::Number, y::Number) in Base at promotion.jl:313

In [55]:
+

+ (generic function with 163 methods)

In [56]:
methods(+)

# 163 methods for generic function "+":
[1] +(x::Bool, z::Complex{Bool}) in Base at complex.jl:277
[2] +(x::Bool, y::Bool) in Base at bool.jl:104
[3] +(x::Bool) in Base at bool.jl:101
[4] +(x::Bool, y::T) where T<:AbstractFloat in Base at bool.jl:112
[5] +(x::Bool, z::Complex) in Base at complex.jl:284
[6] +(a::Float16, b::Float16) in Base at float.jl:392
[7] +(x::Float32, y::Float32) in Base at float.jl:394
[8] +(x::Float64, y::Float64) in Base at float.jl:395
[9] +(z::Complex{Bool}, x::Bool) in Base at complex.jl:278
[10] +(z::Complex{Bool}, x::Real) in Base at complex.jl:292
[11] +(::Missing, ::Missing) in Base at missing.jl:96
[12] +(::Missing) in Base at missing.jl:83
[13] +(::Missing, ::Number) in Base at missing.jl:97
[14] +(level::Base.CoreLogging.LogLevel, inc::Integer) in Base.CoreLogging at logging.jl:106
[15] +(c::BigInt, x::BigFloat) in Base.MPFR at mpfr.jl:406
[16] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) in Base.GMP at gmp.jl:434
[17] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt) in Base.GMP at gmp.jl:433
[18] +(a::BigInt, b::BigInt, c::BigInt) in Base.GMP at gmp.jl:432
[19] +(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:403
[20] +(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.GMP at gmp.jl:440
[21] +(x::BigInt, c::Union{Int16, Int32, Int64, Int8}) in Base.GMP at gmp.jl:446
[22] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) in Base.MPFR at mpfr.jl:556
[23] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) in Base.MPFR at mpfr.jl:549
[24] +(a::BigFloat, b::BigFloat, c::BigFloat) in Base.MPFR at mpfr.jl:543
[25] +(x::BigFloat, c::BigInt) in Base.MPFR at mpfr.jl:402
[26] +(x::BigFloat, y::BigFloat) in Base.MPFR at mpfr.jl:371
[27] +(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.MPFR at mpfr.jl:378
[28] +(x::BigFloat, c::Union{Int16, Int32, Int64, Int8}) in Base.MPFR at mpfr.jl:386
[29] +(x::BigFloat, c::Union{Float16, Float32, Float64}) in Base.MPFR at mpfr.jl:394
[30] +(x::Dates.CompoundPeriod, y::Dates.CompoundPeriod) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:343
[31] +(x::Dates.CompoundPeriod, y::Dates.Period) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:341
[32] +(x::Dates.CompoundPeriod, y::Dates.TimeType) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:371
[33] +(x::Dates.Date, y::Dates.Day) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:74
[34] +(x::Dates.Date, y::Dates.Week) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:72
[35] +(dt::Dates.Date, z::Dates.Month) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:55
[36] +(dt::Dates.Date, y::Dates.Year) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:28
[37] +(dt::Dates.Date, t::Dates.Time) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:19
[38] +(t::Dates.Time, dt::Dates.Date) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:20
[39] +(x::Dates.Time, y::Dates.TimePeriod) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:78
[40] +(dt::Dates.DateTime, z::Dates.Month) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:48
[41] +(dt::Dates.DateTime, y::Dates.Year) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:24
[42] +(x::Dates.DateTime, y::Dates.Period) in Dates at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Dates/src/arithmetic.jl:76
[43] +(B::BitArray{2}, J::LinearAlgebra.UniformScaling) 

## Linear algebra

To use linear algebra functions, use the `LinearAlgebra` package (part of the standard library)

In [57]:
using LinearAlgebra

### Vectors and Matrices

A vector is a uni-dimensional array

In [58]:
Vector{Float32}

Array{Float32,1}

In [59]:
x = [1.0, 2.0]

2-element Array{Float64,1}:
 1.0
 2.0

A matrix is a two-dimensional array

In [60]:
Matrix{Float64}

Array{Float64,2}

In [61]:
A = [
    1.0 2.0;
    3.0 4.0
]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

### Linear algebra operations

Matrix-vector products work out of the box

In [62]:
A * x

2-element Array{Float64,1}:
  5.0
 11.0

Solve linear systems

In [63]:
b = A * x
y = A \ b

2-element Array{Float64,1}:
 1.0
 2.0

You can't multiply two vectors

In [64]:
x * x

MethodError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Adjoint{#s623,#s622} where #s622<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s623, ::Union{DenseArray{S,1}, ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:98
  *(!Matched::Adjoint{#s623,#s622} where #s622<:LinearAlgebra.AbstractTriangular where #s623, ::AbstractArray{T,1} where T) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/triangular.jl:1805
  ...

But inner and outer product is OK

In [65]:
x' * x  # inner product

5.0

In [66]:
x * x'  # outer product

2×2 Array{Float64,2}:
 1.0  2.0
 2.0  4.0

### BLAS / LAPACK

For real/complex numbers in `Float32`, `Float64` precision:
* dense vector-vector, matrix-vector, matrix-matrix operations call BLAS
* dense matrix factorizations call LAPACK

You can also call BLAS/LAPACK functions directly

In [76]:
C = zeros(2, 2);
A = ones(2, 4);
BLAS.syrk!('U', 'N', 1.0, A, 0.0, C)  # computes C = α A*A' + β C

2×2 Array{Float64,2}:
 4.0  4.0
 0.0  4.0

### Sparse linear algebra

In [67]:
using SparseArrays

In [79]:
A = sparse([1, 2, 3], [1, 2, 3], [1.0, 1.0, 1.0])

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  1.0
  [3, 3]  =  1.0

In [80]:
Matrix(A)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

Sparse factorization call the `CHOLMOD` module from `SuiteSparse`.

Community wrappers to MUMPS, Pardiso, HSL linear solvers.

## Package management